-- CreateTable
CREATE TABLE "location" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "location_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "festival" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "year" INT4 NOT NULL,
    "activities" STRING NOT NULL,
    "location_id" INT4 NOT NULL,

    CONSTRAINT "festival_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attendee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" STRING NOT NULL,
    "last_name" STRING NOT NULL,

    CONSTRAINT "attendee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "festival_attendee" (
    "festival_id" INT4 NOT NULL,
    "attendee_id" INT4 NOT NULL,

    CONSTRAINT "festival_attendee_pkey" PRIMARY KEY ("festival_id","attendee_id")
);

-- AddForeignKey
ALTER TABLE "festival" ADD CONSTRAINT "festival_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "location"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "festival_attendee" ADD CONSTRAINT "festival_attendee_festival_id_fkey" FOREIGN KEY ("festival_id") REFERENCES "festival"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "festival_attendee" ADD CONSTRAINT "festival_attendee_attendee_id_fkey" FOREIGN KEY ("attendee_id") REFERENCES "attendee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
